# Generated by Django 5.0.3 on 2024-04-30 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanage', '0002_enseignant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
