# Generated by Django 5.0.3 on 2024-05-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanage', '0005_enseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classematiere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanage.classe_matiere')),
                ('evaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanage.evaluation')),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultats',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True, verbose_name='Note')),
                ('eleve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanage.eleve')),
                ('resultat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanage.resultat')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Note',
            },
        ),
    ]
