# Generated by Django 5.0.3 on 2024-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanage', '0006_resultat_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='filiere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Résultat prédiction'),
        ),
    ]
